name: Daily update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Git config
      run: |-
        git config user.name "Wendy"
        git config user.email "freeman@steamdb.info"
    - name: Run script
      run: ./update.sh
